version: '1'

server:
  path_prefix: '/webhook'
  port: 8080

bridges:
- name: 'example-bridge'
  input:
    source: 'docker-hub'
  output:
    target: 'slack'
    options:
      url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK_URL'
  converter:
    json: |
      {
        "text": "Docker image '{{ .repository.repo_name }}:{{ .push_data.tag }}' built successfully.\n{{ .repository.repo_url }}"
      }
