name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: |
        docker login --username hellodhlyn --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
        docker build -t hellodhlyn/webhook-bridge:latest .
        docker push hellodhlyn/webhook-bridge:latest

        docker tag hellodhlyn/webhook-bridge:latest hellodhlyn/webhook-bridge:${GITHUB_REF##*/}
        docker push hellodhlyn/webhook-bridge:${GITHUB_REF##*/}
